### ISSUE TITLE
Please add some GitHub topics to this repo

### ISSUE THREAD

**Issue by chmac** [vinliao/clust#1]
Firstly, just discovered this from a random search, very cool. I've been thinking a bit about the privacy issue of the relays knowing who is messaging whom. The scheme of deriving a shared key, and then both publishing to that is an interesting one.

Second, would you be up for adding the nostr topic and maybe a few more to this repo? It would make it much easier for folks to find it on GitHub.

**Comment by vinliao** [comment]
Done :)
